# Generated by Django 4.0.8 on 2025-02-05 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ob',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
                ('name', models.TextField()),
            ],
            options={
                'db_table': 'ob',
                'managed': False,
            },
        ),
    ]
