# Generated by Django 4.0.8 on 2025-02-07 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outbound', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ob_today_scandata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
                ('name', models.TextField()),
            ],
        ),
        migrations.AlterModelTable(
            name='ob',
            table='outbound_ob',
        ),
    ]
