# Generated by Django 4.0.8 on 2025-01-21 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bhqr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='today_scandata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('scan_message', models.CharField(max_length=255)),
                ('scan_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
