# Generated by Django 4.0.8 on 2022-11-14 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('성명', models.CharField(blank=True, max_length=10, null=True)),
                ('pw', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': '사용자',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Boxtd',
        ),
    ]
