# Generated by Django 4.0.8 on 2022-11-16 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_users_delete_boxtd'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boxtr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flift', models.CharField(max_length=10)),
                ('truck', models.CharField(max_length=10)),
                ('arrival', models.CharField(blank=True, max_length=10, null=True)),
                ('pub_date', models.DateTimeField()),
                ('wet', models.BooleanField()),
                ('box1', models.CharField(blank=True, max_length=10, null=True)),
                ('box1_qty', models.IntegerField(blank=True, null=True)),
                ('box2', models.CharField(blank=True, max_length=10, null=True)),
                ('box2_qty', models.IntegerField(blank=True, null=True)),
                ('box3', models.CharField(blank=True, max_length=10, null=True)),
                ('box3_qty', models.IntegerField(blank=True, null=True)),
                ('box4', models.CharField(blank=True, max_length=10, null=True)),
                ('box4_qty', models.IntegerField(blank=True, null=True)),
                ('box5', models.CharField(blank=True, max_length=10, null=True)),
                ('box5_qty', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'boxtr',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
