# Generated by Django 4.0.8 on 2022-11-17 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_boxtr_delete_users'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boxtr',
            options={},
        ),
    ]
