# Generated by Django 4.0.8 on 2022-11-18 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_alter_boxtr_arrival_alter_boxtr_box1_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boxtr',
            options={'managed': False},
        ),
    ]
