# Generated by Django 4.0.8 on 2022-11-18 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_alter_boxtr_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boxtr_sum',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('truck', models.CharField(blank=True, max_length=50, null=True)),
                ('arrival', models.CharField(blank=True, choices=[('07:30', '07:30'), ('08:00', '08:00'), ('08:30', '08:30'), ('09:00', '09:00'), ('09:30', '09:30'), ('10:00', '10:00'), ('10:30', '10:30'), ('11:00', '11:00'), ('11:30', '11:30'), ('12:00', '12:00'), ('12:30', '12:30'), ('13:00', '13:00'), ('13:30', '13:30'), ('14:00', '14:00'), ('14:30', '14:30'), ('15:00', '15:00'), ('15:30', '15:30'), ('16:00', '16:00'), ('16:30', '16:30'), ('17:00', '17:00'), ('17:30', '17:30'), ('18:00', '18:00'), ('18:30', '18:30'), ('19:00', '19:00')], max_length=50, null=True)),
                ('pub_date', models.DateTimeField(blank=True, null=True)),
                ('wet', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=50, null=True)),
                ('box', models.CharField(blank=True, max_length=50, null=True)),
                ('box_qty', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'polls_sum',
                'managed': False,
            },
        ),
        migrations.AlterModelTable(
            name='boxtr',
            table='polls_boxtr',
        ),
    ]
