# Generated by Django 4.0.8 on 2022-11-18 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_boxtr_sum_alter_boxtr_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='boxtr_sum',
            table='boxtr_sum',
        ),
    ]
