# Generated by Django 4.0.8 on 2022-11-23 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_alter_boxtr_sum_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boxtr_stock',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user', models.CharField(blank=True, max_length=50, null=True)),
                ('box1', models.CharField(blank=True, choices=[('DN8 TILT', 'DN8 TILT'), ('YF TILT', 'YF TILT'), ('Height', 'Height'), ('LX2_10', 'LX2_10'), ('LX2_12', 'LX2_12'), ('JOEM', 'JOEM'), ('파워내장', '파워내장'), ('파워일반', '파워일반'), ('파워포장', '파워포장'), ('PU', 'PU'), ('XMA', 'XMA'), ('일반히터', '일반히터'), ('GPB', 'GPB'), ('GPG', 'GPG'), ('기타', '기타')], max_length=50, null=True)),
                ('pub_date', models.DateTimeField(blank=True, null=True)),
                ('box_qty', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
