# Generated by Django 4.0.8 on 2022-11-23 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_boxtr_stock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boxtr_stock',
            old_name='box1',
            new_name='box',
        ),
    ]
