# Generated by Django 4.0.8 on 2022-11-23 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0013_rename_box1_boxtr_stock_box'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boxtr_stock',
            name='box',
            field=models.CharField(blank=True, choices=[('DN8 TILT', 'DN8_TILT'), ('YF TILT', 'YF_TILT'), ('Height', 'Height'), ('LX2_10', 'LX2_10'), ('LX2_12', 'LX2_12'), ('JOEM', 'JOEM'), ('파워내장', '파워내장'), ('파워일반', '파워일반'), ('파워포장', '파워포장'), ('PU', 'PU'), ('XMA', 'XMA'), ('일반히터', '일반히터'), ('GPB', 'GPB'), ('GPG', 'GPG'), ('PS', 'PS'), ('기타', '기타')], max_length=50, null=True),
        ),
    ]
