# Generated by Django 4.0.8 on 2022-11-24 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0014_alter_boxtr_stock_box'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boxtr_stock',
            options={'managed': False},
        ),
    ]
