# Generated by Django 4.0.8 on 2022-11-24 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0015_alter_boxtr_stock_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='boxtr_stock',
            table='boxtr_stock',
        ),
    ]
