# Generated by Django 4.0.8 on 2022-11-24 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0016_alter_boxtr_stock_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boxtr_status',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('truck', models.CharField(blank=True, max_length=50, null=True)),
                ('arrival', models.CharField(blank=True, max_length=50, null=True)),
                ('pub_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('wet', models.CharField(blank=True, max_length=50, null=True)),
                ('box1', models.CharField(blank=True, max_length=50, null=True)),
                ('box1_qty', models.IntegerField(blank=True, null=True)),
                ('box2', models.CharField(blank=True, max_length=50, null=True)),
                ('box2_qty', models.IntegerField(blank=True, null=True)),
                ('box3', models.CharField(blank=True, max_length=50, null=True)),
                ('box3_qty', models.IntegerField(blank=True, null=True)),
                ('box4', models.CharField(blank=True, max_length=50, null=True)),
                ('box4_qty', models.IntegerField(blank=True, null=True)),
                ('box5', models.CharField(blank=True, max_length=50, null=True)),
                ('box5_qty', models.IntegerField(blank=True, null=True)),
                ('qty', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'boxtr_status',
                'managed': False,
            },
        ),
    ]
